# Data Analytics
- Numpy
- Scipy
- matplotlib
- pandas
- seaborn
- scrapy
- beautifulsoap
- selenium
- scikit-learn

In [1]:
import numpy as np

In [2]:
np.random.random((2,2))

array([[0.24663529, 0.71337424],
       [0.08287061, 0.87222113]])

###### print("Hello World")

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

| This | is   |
|------|------|
|   a  | table|

<img src="https://www.numpy.org/_static/numpy_logo.png" width="400" height="200"><br>
# Numpy
-pip install numpy==1.4.0

In [3]:
# import numpy
import numpy as np

In [4]:
# print(numpy.__version__)
print(np.__version__)

1.16.2


In [5]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [6]:
a = [1,2,3,4,5,6,7]

In [7]:
b = np.arange(1,8)

In [8]:
print(type(a))
print(a)

<class 'list'>
[1, 2, 3, 4, 5, 6, 7]


In [9]:
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [10]:
print(len(a))
print(len(b))

7
7


In [11]:
import sys

In [12]:
sys.getsizeof(a)

120

In [13]:
# a.__sizeof__()

In [14]:
sys.getsizeof(a[0])

28

In [15]:
b[0]

1

In [16]:
a[0]

1

In [17]:
b.itemsize

4

In [18]:
x=list(range(1000))

In [19]:
y=np.arange(1000)

In [20]:
timeit [i**2 for i in x]

866 µs ± 32.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
timeit y**2

3.3 µs ± 215 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
a

[1, 2, 3, 4, 5, 6, 7]

In [23]:
a*2

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]

In [24]:
b

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
b*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [26]:
b**2

array([ 1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [27]:
import math

In [28]:
print(np.power)
print(math.pow)
print(pow)

<ufunc 'power'>
<built-in function pow>
<built-in function pow>


In [29]:
np.power(a,5)

array([    1,    32,   243,  1024,  3125,  7776, 16807], dtype=int32)

In [30]:
b **5

array([    1,    32,   243,  1024,  3125,  7776, 16807], dtype=int32)

In [31]:
a

[1, 2, 3, 4, 5, 6, 7]

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arr -2 

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [36]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [37]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [38]:
arr // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [39]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [40]:
arr.dtype

dtype('int32')

In [41]:
arr.ndim

1

In [42]:
arr.shape

(10,)

In [43]:
arr.itemsize

4

In [44]:
arr.dtype

dtype('int32')

In [45]:
arr_64 = arr.astype('int64')
arr_64

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [46]:
arr_64.dtype

dtype('int64')

In [47]:
arr_64.itemsize

8

In [48]:
# indexing / slicing

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr.size

10

In [51]:
len(arr)

10

In [52]:
arr[-2]

8

In [53]:
# arr[10]

In [54]:
arr[:2]

array([0, 1])

In [55]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[9:12]

array([9])

In [57]:
arr[9:120]

array([9])

In [58]:
arr[1:3:-1]

array([], dtype=int32)

In [59]:
arr[:3:-1]

array([9, 8, 7, 6, 5, 4])

In [60]:
arr[1::-1]

array([1, 0])

In [61]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [62]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr.size

10

In [64]:
x = arr.reshape(5,2)
# print(x)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
y = arr.resize(5,2)
y

In [67]:
print(y)

None


In [68]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [69]:
arr.size

10

In [70]:
len(arr)

5

In [71]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [72]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
arr = arr.ravel()

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
# import random

In [78]:
a = np.random.random((10))
a

array([0.46192663, 0.05666798, 0.05436045, 0.87665144, 0.12507546,
       0.5276922 , 0.42594403, 0.81104862, 0.69930942, 0.10006439])

In [79]:
a.ndim

1

In [80]:
a = np.random.random((4,5))
a

array([[0.8171119 , 0.6267894 , 0.44454771, 0.60295397, 0.91238809],
       [0.50874352, 0.32833247, 0.2171944 , 0.54715593, 0.33705917],
       [0.32306937, 0.61188695, 0.04942588, 0.12371895, 0.42388013],
       [0.3690332 , 0.16554308, 0.94230066, 0.6503616 , 0.56483071]])

In [81]:
a.size

20

In [82]:
a.ndim

2

In [83]:
a.shape

(4, 5)

In [84]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a

array([[0.8171119 , 0.6267894 , 0.44454771, 0.60295397, 0.91238809],
       [0.50874352, 0.32833247, 0.2171944 , 0.54715593, 0.33705917],
       [0.32306937, 0.61188695, 0.04942588, 0.12371895, 0.42388013],
       [0.3690332 , 0.16554308, 0.94230066, 0.6503616 , 0.56483071]])

In [86]:
b = list([[0.83674933, 0.27957488, 0.99827947, 0.04480981, 0.67602971],
       [0.33653568, 0.98117748, 0.96532634, 0.13991943, 0.5286535 ],
       [0.81161537, 0.97437482, 0.39446133, 0.28865976, 0.5631383 ],
       [0.70592881, 0.43930533, 0.90170558, 0.45247481, 0.80866967]])

In [87]:
b

[[0.83674933, 0.27957488, 0.99827947, 0.04480981, 0.67602971],
 [0.33653568, 0.98117748, 0.96532634, 0.13991943, 0.5286535],
 [0.81161537, 0.97437482, 0.39446133, 0.28865976, 0.5631383],
 [0.70592881, 0.43930533, 0.90170558, 0.45247481, 0.80866967]]

In [88]:
import time

In [89]:
def fun(x):
#     print(">>>>",x)
#     time.sleep(1)

    return  [int(str(i)[-1]) for i in x]

In [90]:
np.array(list(map(fun, b)))

array([[3, 8, 7, 1, 1],
       [8, 8, 4, 3, 5],
       [7, 2, 3, 6, 3],
       [1, 3, 8, 1, 7]])

In [91]:
str(0.3456)

'0.3456'

In [92]:
np.array(list(map(lambda x: [int(str(i)[-1]) for i in x], b)))

array([[3, 8, 7, 1, 1],
       [8, 8, 4, 3, 5],
       [7, 2, 3, 6, 3],
       [1, 3, 8, 1, 7]])

In [93]:
def task(x):
    a=[]
    for i in x:
        if i=='{':
            a.append(1)
        elif i=='}':
            if len(a)<1:
                return False
            a.pop()
            
    if len(a)==0:
        return True
    return False

In [94]:
task('{}{}')

True

In [95]:
import itertools

In [96]:
print(dir(itertools))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', '_grouper', '_tee', '_tee_dataobject', 'accumulate', 'chain', 'combinations', 'combinations_with_replacement', 'compress', 'count', 'cycle', 'dropwhile', 'filterfalse', 'groupby', 'islice', 'permutations', 'product', 'repeat', 'starmap', 'takewhile', 'tee', 'zip_longest']


In [97]:
import numpy as np

In [98]:
arr = np.array([1,2,3])

In [99]:
arr

array([1, 2, 3])

In [100]:
arr.shape

(3,)

In [101]:
arr.ndim

1

In [102]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
arr.shape

(3, 3)

In [104]:
arr.dtype

dtype('int32')

In [105]:
a = np.arange(300,1000,100)

In [106]:
a

array([300, 400, 500, 600, 700, 800, 900])

In [107]:
a.shape

(7,)

In [108]:
a.dtype

dtype('int32')

In [109]:
a.astype('int8')

array([  44, -112,  -12,   88,  -68,   32, -124], dtype=int8)

In [110]:
b= np.array([128])
b

array([128])

In [111]:
b.dtype

dtype('int32')

In [112]:
b.astype('int8')

array([-128], dtype=int8)

In [113]:
b= np.array([127])
b

array([127])

In [114]:
b.dtype

dtype('int32')

In [115]:
b.astype('int8')

array([127], dtype=int8)

In [116]:
c=np.array([130])
c

array([130])

In [117]:
c.dtype

dtype('int32')

In [118]:
c.astype('int8')

array([-126], dtype=int8)

In [119]:
~5

-6

In [120]:
c.astype('int16')

array([130], dtype=int16)

In [121]:
# c.astype('int9')

In [122]:
c.dtype

dtype('int32')

In [123]:
c.itemsize

4

In [124]:
c= c.astype(np.int16)

In [125]:
c.itemsize

2

In [126]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
arr.ndim

2

In [128]:
arr.shape

(3, 3)

In [129]:
arr[1][2]

6

In [130]:
arr[1,2]

6

In [131]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [133]:
print(np.array([arr[1][1:],arr[2][1:]]))

[[5 6]
 [8 9]]


In [134]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [135]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
arr=np.arange(1,43)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42])

In [137]:
arr.size

42

In [138]:
arr.resize(7,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42]])

In [139]:
arr[-3:,-3:]

array([[28, 29, 30],
       [34, 35, 36],
       [40, 41, 42]])

In [140]:
arr[:,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35],
       [37, 39, 41]])

In [141]:
arr[:,0]

array([ 1,  7, 13, 19, 25, 31, 37])

In [142]:
arr[:,[0]]

array([[ 1],
       [ 7],
       [13],
       [19],
       [25],
       [31],
       [37]])

In [143]:
arr[:,[0,3,4]]

array([[ 1,  4,  5],
       [ 7, 10, 11],
       [13, 16, 17],
       [19, 22, 23],
       [25, 28, 29],
       [31, 34, 35],
       [37, 40, 41]])

In [144]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42]])

In [145]:
arr[-1,[0,3,4]]

array([37, 40, 41])

In [146]:
arr[[-1],[0,3,4]]

array([37, 40, 41])

In [147]:
arr[-1:,[0,3,4]]

array([[37, 40, 41]])

In [148]:
arr[-2,[0,3,4]]

array([31, 34, 35])

In [149]:
arr[-2:-1,[0,3,4]]

array([[31, 34, 35]])

In [150]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42]])

In [151]:
arr[-2:-1:-1,[0,3,4]]

array([], shape=(0, 3), dtype=int32)

In [152]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42]])

In [153]:
arr.shape

(7, 6)

In [154]:
arr.size

42

In [155]:
len(arr)

7

In [156]:
a = arr.ravel()

In [157]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42])

In [158]:
a.reshape(6,-1)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [159]:
a.reshape(-1,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [160]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42])

In [161]:
a.ndim

1

In [162]:
a.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42]])

In [163]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40],
       [41, 42]])

In [164]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42])

In [165]:
# import random

In [166]:
np.random.shuffle(a)

In [167]:
a

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13,  2, 10,  9,  7,
       25, 18, 21, 34, 33,  3, 19, 40,  4,  1, 36, 37, 32, 22, 41, 14, 24,
        6, 29,  8,  5, 35, 38, 15, 11])

In [168]:
a_even = [i for i in a if i%2==0]
a_odd = [i for i in a if i%2==1]

In [169]:
print(a_even)
print(a_odd)

[20, 26, 30, 12, 16, 42, 28, 2, 10, 18, 34, 40, 4, 36, 32, 22, 14, 24, 6, 8, 38]
[27, 23, 39, 17, 31, 13, 9, 7, 25, 21, 33, 3, 19, 1, 37, 41, 29, 5, 35, 15, 11]


In [170]:
x=np.arange(1,5)
x

array([1, 2, 3, 4])

In [171]:
np.append(x,10)

array([ 1,  2,  3,  4, 10])

In [172]:
x = np.append(x,10)

In [173]:
x

array([ 1,  2,  3,  4, 10])

In [174]:
x_even=np.array([])
x_odd = np.array([])

In [175]:
x_even

array([], dtype=float64)

In [176]:
x_odd

array([], dtype=float64)

In [177]:
a

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13,  2, 10,  9,  7,
       25, 18, 21, 34, 33,  3, 19, 40,  4,  1, 36, 37, 32, 22, 41, 14, 24,
        6, 29,  8,  5, 35, 38, 15, 11])

In [178]:
for i in a:
    if i%2==0:
        x_even=np.append(x_even, i)
    else:
        x_odd=np.append(x_odd, i)
print(x_even)
print(x_odd)

[20. 26. 30. 12. 16. 42. 28.  2. 10. 18. 34. 40.  4. 36. 32. 22. 14. 24.
  6.  8. 38.]
[27. 23. 39. 17. 31. 13.  9.  7. 25. 21. 33.  3. 19.  1. 37. 41. 29.  5.
 35. 15. 11.]


In [179]:
a_even=list(filter(lambda x:x%2==0, a))
a_odd=list(filter(lambda x:x%2==1, a))
print(a_even)
print(a_odd)

[20, 26, 30, 12, 16, 42, 28, 2, 10, 18, 34, 40, 4, 36, 32, 22, 14, 24, 6, 8, 38]
[27, 23, 39, 17, 31, 13, 9, 7, 25, 21, 33, 3, 19, 1, 37, 41, 29, 5, 35, 15, 11]


In [180]:
a

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13,  2, 10,  9,  7,
       25, 18, 21, 34, 33,  3, 19, 40,  4,  1, 36, 37, 32, 22, 41, 14, 24,
        6, 29,  8,  5, 35, 38, 15, 11])

In [181]:
a>10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True,  True, False,  True,  True, False, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True])

In [182]:
a

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13,  2, 10,  9,  7,
       25, 18, 21, 34, 33,  3, 19, 40,  4,  1, 36, 37, 32, 22, 41, 14, 24,
        6, 29,  8,  5, 35, 38, 15, 11])

In [183]:
a[[False,  True,  True, False,  True,  True, False,  True, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False]]

array([27, 26, 30, 12, 17, 42, 28, 13, 10,  9,  7, 25, 21, 34, 33,  3, 19,
       40,  4, 36, 37, 32, 22, 41, 14, 24,  6, 29,  8,  5, 38, 15])

In [184]:
a[a>10]

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13, 25, 18, 21, 34,
       33, 19, 40, 36, 37, 32, 22, 41, 14, 24, 29, 35, 38, 15, 11])

In [185]:
a%2==0

array([ True, False,  True, False,  True,  True, False, False,  True,
        True, False,  True, False,  True,  True, False, False, False,
        True, False,  True, False, False, False,  True,  True, False,
        True, False,  True,  True, False,  True,  True,  True, False,
        True, False, False,  True, False, False])

In [186]:
a[a%2==0]

array([20, 26, 30, 12, 16, 42, 28,  2, 10, 18, 34, 40,  4, 36, 32, 22, 14,
       24,  6,  8, 38])

In [187]:
a[a%2==1]

array([27, 23, 39, 17, 31, 13,  9,  7, 25, 21, 33,  3, 19,  1, 37, 41, 29,
        5, 35, 15, 11])

# Fancing Index

In [188]:
arr

array([[20, 27, 26, 23, 30, 12],
       [39, 17, 16, 42, 31, 28],
       [13,  2, 10,  9,  7, 25],
       [18, 21, 34, 33,  3, 19],
       [40,  4,  1, 36, 37, 32],
       [22, 41, 14, 24,  6, 29],
       [ 8,  5, 35, 38, 15, 11]])

In [189]:
arr>10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False,  True],
       [ True,  True,  True,  True, False,  True],
       [ True, False, False,  True,  True,  True],
       [ True,  True,  True,  True, False,  True],
       [False, False,  True,  True,  True,  True]])

In [190]:
arr[arr>10]

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13, 25, 18, 21, 34,
       33, 19, 40, 36, 37, 32, 22, 41, 14, 24, 29, 35, 38, 15, 11])

In [191]:
arr

array([[20, 27, 26, 23, 30, 12],
       [39, 17, 16, 42, 31, 28],
       [13,  2, 10,  9,  7, 25],
       [18, 21, 34, 33,  3, 19],
       [40,  4,  1, 36, 37, 32],
       [22, 41, 14, 24,  6, 29],
       [ 8,  5, 35, 38, 15, 11]])

In [192]:
arr[[1,2],[4,1]]

array([31,  2])

In [193]:
x=np.arange(1,5).reshape(2,-1)
x

array([[1, 2],
       [3, 4]])

In [194]:
y=np.arange(4,0,-1).reshape(2,-1)
y

array([[4, 3],
       [2, 1]])

In [195]:
arr

array([[20, 27, 26, 23, 30, 12],
       [39, 17, 16, 42, 31, 28],
       [13,  2, 10,  9,  7, 25],
       [18, 21, 34, 33,  3, 19],
       [40,  4,  1, 36, 37, 32],
       [22, 41, 14, 24,  6, 29],
       [ 8,  5, 35, 38, 15, 11]])

In [196]:
arr[x,y]

array([[31,  9],
       [34,  4]])

In [197]:
np.arange(1,4,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8])

In [198]:
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [199]:
np.random.random(10)

array([0.36211269, 0.03808555, 0.41172363, 0.57714876, 0.97639634,
       0.5830822 , 0.18894404, 0.10662809, 0.42479682, 0.94818665])

In [200]:
np.random.random((3,4))

array([[0.61667964, 0.25156251, 0.26133099, 0.85589723],
       [0.17583237, 0.58807318, 0.60166992, 0.40738427],
       [0.9123135 , 0.66449285, 0.01279225, 0.61296718]])

In [201]:
np.random.randint(1,100,(5,6))

array([[77, 72, 48, 98,  5,  6],
       [92, 52,  9, 58, 66, 67],
       [43, 44,  3, 45, 84, 68],
       [99, 54, 72, 22, 92, 81],
       [32, 44, 44, 33, 57, 48]])

In [202]:
a

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13,  2, 10,  9,  7,
       25, 18, 21, 34, 33,  3, 19, 40,  4,  1, 36, 37, 32, 22, 41, 14, 24,
        6, 29,  8,  5, 35, 38, 15, 11])

In [203]:
a.max()

42

In [204]:
a.min()

1

In [205]:
a.mean()

21.5

In [206]:
a.std()

12.120918557051139

In [207]:
a.var()

146.91666666666666

In [208]:
np.median(a)

21.5

In [209]:
np.max(a)

42

In [210]:
a

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13,  2, 10,  9,  7,
       25, 18, 21, 34, 33,  3, 19, 40,  4,  1, 36, 37, 32, 22, 41, 14, 24,
        6, 29,  8,  5, 35, 38, 15, 11])

In [211]:
b=a.reshape(6,-1)
b

array([[20, 27, 26, 23, 30, 12, 39],
       [17, 16, 42, 31, 28, 13,  2],
       [10,  9,  7, 25, 18, 21, 34],
       [33,  3, 19, 40,  4,  1, 36],
       [37, 32, 22, 41, 14, 24,  6],
       [29,  8,  5, 35, 38, 15, 11]])

In [212]:
b.mean()

21.5

In [213]:
b.mean(axis=0)

array([24.33333333, 15.83333333, 20.16666667, 32.5       , 22.        ,
       14.33333333, 21.33333333])

In [214]:
b.mean(axis=1)

array([25.28571429, 21.28571429, 17.71428571, 19.42857143, 25.14285714,
       20.14285714])

In [215]:
np.square(a)

array([ 400,  729,  676,  529,  900,  144, 1521,  289,  256, 1764,  961,
        784,  169,    4,  100,   81,   49,  625,  324,  441, 1156, 1089,
          9,  361, 1600,   16,    1, 1296, 1369, 1024,  484, 1681,  196,
        576,   36,  841,   64,   25, 1225, 1444,  225,  121], dtype=int32)

In [216]:
np.sqrt(a)

array([4.47213595, 5.19615242, 5.09901951, 4.79583152, 5.47722558,
       3.46410162, 6.244998  , 4.12310563, 4.        , 6.4807407 ,
       5.56776436, 5.29150262, 3.60555128, 1.41421356, 3.16227766,
       3.        , 2.64575131, 5.        , 4.24264069, 4.58257569,
       5.83095189, 5.74456265, 1.73205081, 4.35889894, 6.32455532,
       2.        , 1.        , 6.        , 6.08276253, 5.65685425,
       4.69041576, 6.40312424, 3.74165739, 4.89897949, 2.44948974,
       5.38516481, 2.82842712, 2.23606798, 5.91607978, 6.164414  ,
       3.87298335, 3.31662479])

In [217]:
a**2

array([ 400,  729,  676,  529,  900,  144, 1521,  289,  256, 1764,  961,
        784,  169,    4,  100,   81,   49,  625,  324,  441, 1156, 1089,
          9,  361, 1600,   16,    1, 1296, 1369, 1024,  484, 1681,  196,
        576,   36,  841,   64,   25, 1225, 1444,  225,  121], dtype=int32)

In [218]:
a**0.5

array([4.47213595, 5.19615242, 5.09901951, 4.79583152, 5.47722558,
       3.46410162, 6.244998  , 4.12310563, 4.        , 6.4807407 ,
       5.56776436, 5.29150262, 3.60555128, 1.41421356, 3.16227766,
       3.        , 2.64575131, 5.        , 4.24264069, 4.58257569,
       5.83095189, 5.74456265, 1.73205081, 4.35889894, 6.32455532,
       2.        , 1.        , 6.        , 6.08276253, 5.65685425,
       4.69041576, 6.40312424, 3.74165739, 4.89897949, 2.44948974,
       5.38516481, 2.82842712, 2.23606798, 5.91607978, 6.164414  ,
       3.87298335, 3.31662479])

In [219]:
a**(1/3)

array([2.71441762, 3.        , 2.96249607, 2.84386698, 3.10723251,
       2.28942849, 3.39121144, 2.57128159, 2.5198421 , 3.47602664,
       3.14138065, 3.03658897, 2.35133469, 1.25992105, 2.15443469,
       2.08008382, 1.91293118, 2.92401774, 2.62074139, 2.75892418,
       3.2396118 , 3.20753433, 1.44224957, 2.66840165, 3.41995189,
       1.58740105, 1.        , 3.30192725, 3.33222185, 3.1748021 ,
       2.80203933, 3.44821724, 2.41014226, 2.88449914, 1.81712059,
       3.07231683, 2.        , 1.70997595, 3.27106631, 3.36197541,
       2.46621207, 2.22398009])

In [220]:
5 in a

True

In [221]:
a

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13,  2, 10,  9,  7,
       25, 18, 21, 34, 33,  3, 19, 40,  4,  1, 36, 37, 32, 22, 41, 14, 24,
        6, 29,  8,  5, 35, 38, 15, 11])

In [222]:
b

array([[20, 27, 26, 23, 30, 12, 39],
       [17, 16, 42, 31, 28, 13,  2],
       [10,  9,  7, 25, 18, 21, 34],
       [33,  3, 19, 40,  4,  1, 36],
       [37, 32, 22, 41, 14, 24,  6],
       [29,  8,  5, 35, 38, 15, 11]])

In [223]:
b.T

array([[20, 17, 10, 33, 37, 29],
       [27, 16,  9,  3, 32,  8],
       [26, 42,  7, 19, 22,  5],
       [23, 31, 25, 40, 41, 35],
       [30, 28, 18,  4, 14, 38],
       [12, 13, 21,  1, 24, 15],
       [39,  2, 34, 36,  6, 11]])

In [224]:
b.transpose()

array([[20, 17, 10, 33, 37, 29],
       [27, 16,  9,  3, 32,  8],
       [26, 42,  7, 19, 22,  5],
       [23, 31, 25, 40, 41, 35],
       [30, 28, 18,  4, 14, 38],
       [12, 13, 21,  1, 24, 15],
       [39,  2, 34, 36,  6, 11]])

In [225]:
np.transpose(b)

array([[20, 17, 10, 33, 37, 29],
       [27, 16,  9,  3, 32,  8],
       [26, 42,  7, 19, 22,  5],
       [23, 31, 25, 40, 41, 35],
       [30, 28, 18,  4, 14, 38],
       [12, 13, 21,  1, 24, 15],
       [39,  2, 34, 36,  6, 11]])

In [226]:
x

array([[1, 2],
       [3, 4]])

In [227]:
y

array([[4, 3],
       [2, 1]])

In [228]:
x.dot(y)

array([[ 8,  5],
       [20, 13]])

In [229]:
np.multiply(x,y)

array([[4, 6],
       [6, 4]])

In [230]:
x*y

array([[4, 6],
       [6, 4]])

In [231]:
x*4

array([[ 4,  8],
       [12, 16]])

In [232]:
b

array([[20, 27, 26, 23, 30, 12, 39],
       [17, 16, 42, 31, 28, 13,  2],
       [10,  9,  7, 25, 18, 21, 34],
       [33,  3, 19, 40,  4,  1, 36],
       [37, 32, 22, 41, 14, 24,  6],
       [29,  8,  5, 35, 38, 15, 11]])

In [233]:
b.diagonal()

array([20, 16,  7, 40, 14, 15])

In [234]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [235]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [236]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [237]:
np.diag([3,1,5,6])

array([[3, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [238]:
a

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13,  2, 10,  9,  7,
       25, 18, 21, 34, 33,  3, 19, 40,  4,  1, 36, 37, 32, 22, 41, 14, 24,
        6, 29,  8,  5, 35, 38, 15, 11])

In [239]:
c=a[:36].reshape(6,-1)
c

array([[20, 27, 26, 23, 30, 12],
       [39, 17, 16, 42, 31, 28],
       [13,  2, 10,  9,  7, 25],
       [18, 21, 34, 33,  3, 19],
       [40,  4,  1, 36, 37, 32],
       [22, 41, 14, 24,  6, 29]])

In [240]:
c * np.eye(6)

array([[20.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 17.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 33.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 37.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 29.]])

In [241]:
p1=np.array([2,3])
p2=np.array([4,5])

In [242]:
p1-p2

array([-2, -2])

In [243]:
np.sqrt(np.square(p1[0]-p2[0])+np.square(p1[1]-p2[1]))

2.8284271247461903

In [244]:
np.sqrt(np.square((p1-p2)[0])+np.square((p1-p2)[1]))

2.8284271247461903

In [245]:
np.linalg.norm(p1-p2)

2.8284271247461903

In [246]:
p = np.array([1,2,3], dtype='int8')
p

array([1, 2, 3], dtype=int8)

In [247]:
p.dtype

dtype('int8')

In [248]:
q=np.empty(8)
q

array([0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000,
       5.257e-321, 0.000e+000, 0.000e+000])

In [249]:
q.itemsize

8

In [250]:
q.dtype

dtype('float64')

In [251]:
from numpy import pi

In [252]:
pi

3.141592653589793

In [253]:
np.pi

3.141592653589793

In [254]:
x

array([[1, 2],
       [3, 4]])

In [255]:
y

array([[4, 3],
       [2, 1]])

In [256]:
x@y

array([[ 8,  5],
       [20, 13]])

In [257]:
def fun(x,y):
    return x+y

In [258]:
np.fromfunction(fun,(3,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [259]:
a

array([20, 27, 26, 23, 30, 12, 39, 17, 16, 42, 31, 28, 13,  2, 10,  9,  7,
       25, 18, 21, 34, 33,  3, 19, 40,  4,  1, 36, 37, 32, 22, 41, 14, 24,
        6, 29,  8,  5, 35, 38, 15, 11])

In [260]:
x

array([[1, 2],
       [3, 4]])

In [261]:
x.flatten()

array([1, 2, 3, 4])

In [262]:
for i in x.flat:
    print(i)

1
2
3
4


In [263]:
a=x.flat

In [264]:
next(a)

1

In [265]:
next(a)

2

In [266]:
np

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [267]:
import numpy as np

In [269]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [270]:
arr = np.arange(30,40)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [271]:
np.max(arr)

39

In [272]:
np.argmax(arr)

9

In [274]:
np.random.shuffle(arr)
arr

array([36, 34, 33, 31, 32, 30, 39, 38, 37, 35])

In [275]:
np.argmax(arr)

6

In [276]:
np.argmin(arr)

5

In [277]:
arr.dtype

dtype('int32')

In [278]:
arr.dtype.name

'int32'

In [280]:
print(dir(arr.dtype))

['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'alignment', 'base', 'byteorder', 'char', 'descr', 'fields', 'flags', 'hasobject', 'isalignedstruct', 'isbuiltin', 'isnative', 'itemsize', 'kind', 'metadata', 'name', 'names', 'ndim', 'newbyteorder', 'num', 'shape', 'str', 'subdtype', 'type']


In [281]:
mat = np.arange(42)
np.random.shuffle(mat)
mat = mat.reshape(6,-1)
mat

array([[33,  6, 21, 13, 30, 40,  4],
       [14, 16,  5, 23,  3, 24, 36],
       [38,  2, 26, 12, 31, 22, 28],
       [35, 15, 37, 41, 10,  0, 27],
       [18, 25, 29, 32, 34, 19,  8],
       [17,  1, 20,  9, 11,  7, 39]])

In [282]:
mat.cumsum()

array([ 33,  39,  60,  73, 103, 143, 147, 161, 177, 182, 205, 208, 232,
       268, 306, 308, 334, 346, 377, 399, 427, 462, 477, 514, 555, 565,
       565, 592, 610, 635, 664, 696, 730, 749, 757, 774, 775, 795, 804,
       815, 822, 861], dtype=int32)

In [283]:
mat.sum()

861

In [285]:
mat[:,2]

array([21,  5, 26, 37, 29, 20])

In [284]:
mat[2]

array([38,  2, 26, 12, 31, 22, 28])

In [ ]:
mat.cumsum(axix=0)

In [286]:
mat

array([[33,  6, 21, 13, 30, 40,  4],
       [14, 16,  5, 23,  3, 24, 36],
       [38,  2, 26, 12, 31, 22, 28],
       [35, 15, 37, 41, 10,  0, 27],
       [18, 25, 29, 32, 34, 19,  8],
       [17,  1, 20,  9, 11,  7, 39]])

In [287]:
mat.sum()

861

In [288]:
mat.sum(axis=0)

array([155,  65, 138, 130, 119, 112, 142])

In [289]:
mat.cumsum(axis=1)

array([[ 33,  39,  60,  73, 103, 143, 147],
       [ 14,  30,  35,  58,  61,  85, 121],
       [ 38,  40,  66,  78, 109, 131, 159],
       [ 35,  50,  87, 128, 138, 138, 165],
       [ 18,  43,  72, 104, 138, 157, 165],
       [ 17,  18,  38,  47,  58,  65, 104]], dtype=int32)

In [290]:
mat

array([[33,  6, 21, 13, 30, 40,  4],
       [14, 16,  5, 23,  3, 24, 36],
       [38,  2, 26, 12, 31, 22, 28],
       [35, 15, 37, 41, 10,  0, 27],
       [18, 25, 29, 32, 34, 19,  8],
       [17,  1, 20,  9, 11,  7, 39]])

In [293]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [295]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [296]:
# e^x

In [297]:
2.71828183**2

7.389056107308149

In [298]:
a

array([0, 1, 2, 3, 4])

In [299]:
a[:2]=100

In [300]:
a

array([100, 100,   2,   3,   4])

In [301]:
a[:]=200

In [302]:
a

array([200, 200, 200, 200, 200])

In [303]:
arr

array([36, 34, 33, 31, 32, 30, 39, 38, 37, 35])

In [304]:
mat

array([[33,  6, 21, 13, 30, 40,  4],
       [14, 16,  5, 23,  3, 24, 36],
       [38,  2, 26, 12, 31, 22, 28],
       [35, 15, 37, 41, 10,  0, 27],
       [18, 25, 29, 32, 34, 19,  8],
       [17,  1, 20,  9, 11,  7, 39]])

In [305]:
b=mat[-3:,-3:]
b

array([[10,  0, 27],
       [34, 19,  8],
       [11,  7, 39]])

In [306]:
b[:]=0

In [308]:
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [307]:
mat

array([[33,  6, 21, 13, 30, 40,  4],
       [14, 16,  5, 23,  3, 24, 36],
       [38,  2, 26, 12, 31, 22, 28],
       [35, 15, 37, 41,  0,  0,  0],
       [18, 25, 29, 32,  0,  0,  0],
       [17,  1, 20,  9,  0,  0,  0]])

In [309]:
b[-1:,-1]

array([0])

In [310]:
id(b[-1:,-1])

1313349682640

In [311]:
id(mat[-1:,-1])

1313349682080

In [312]:
x=90

In [313]:
id(x)

140727944191584

In [314]:
y=x

In [315]:
id(y)

140727944191584

In [316]:
id(90)

140727944191584

In [317]:
mat

array([[33,  6, 21, 13, 30, 40,  4],
       [14, 16,  5, 23,  3, 24, 36],
       [38,  2, 26, 12, 31, 22, 28],
       [35, 15, 37, 41,  0,  0,  0],
       [18, 25, 29, 32,  0,  0,  0],
       [17,  1, 20,  9,  0,  0,  0]])

In [318]:
id(mat[1,1])

1313352303096

In [321]:
mat[1,1]

16

In [319]:
x=mat[:2,:2]
x

array([[33,  6],
       [14, 16]])

In [320]:
id(x[1,1])

1313352303144

In [325]:
x[1,1]=90

In [322]:
x[1,1]

16

In [326]:
mat

array([[33,  6, 21, 13, 30, 40,  4],
       [14, 90,  5, 23,  3, 24, 36],
       [38,  2, 26, 12, 31, 22, 28],
       [35, 15, 37, 41,  0,  0,  0],
       [18, 25, 29, 32,  0,  0,  0],
       [17,  1, 20,  9,  0,  0,  0]])

In [323]:
np.may_share_memory(mat, x)

True

In [324]:
np.shares_memory(mat, x)

True

In [327]:
import math

In [328]:
print(math)

<module 'math' (built-in)>


In [330]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [331]:
math.floor(89.45677)

89

In [332]:
math.ceil(89.2345)

90

In [333]:
math.floor(89.99997)

89

In [334]:
round(89.99997)

90

In [336]:
round(89.49997)

89.0

In [337]:
round(89.5000)

90

In [339]:
round(89.49997,1)

89.5

In [340]:
np.round(89.49999)

89.0

In [341]:
np.round(89.49999,1)

89.5

In [342]:
np.floor(89.49999)

89.0

In [343]:
np.ceil(89.49999)

90.0

In [349]:
np.random.random((3,4))

array([[0.72840828, 0.45765626, 0.45006149, 0.32742194],
       [0.59267364, 0.30852401, 0.71231925, 0.04416773],
       [0.81365339, 0.86301318, 0.3732439 , 0.17177001]])

In [350]:
a = np.floor(10*np.random.random((3,4)))

In [351]:
a

array([[4., 1., 7., 1.],
       [5., 2., 3., 9.],
       [8., 2., 2., 9.]])

In [357]:
np.random.seed(100)
a = np.floor(10*np.random.random((3,4)))
a

array([[5., 2., 4., 8.],
       [0., 1., 6., 8.],
       [1., 5., 8., 2.]])

In [360]:
np.random.seed(101)
a = np.floor(10*np.random.random((3,4)))
a

array([[5., 5., 0., 1.],
       [6., 8., 3., 8.],
       [7., 1., 5., 3.]])

In [361]:
np.random.seed(101)
a = np.floor(10*np.random.random((3,4)))
a

array([[5., 5., 0., 1.],
       [6., 8., 3., 8.],
       [7., 1., 5., 3.]])

In [363]:
np.random.seed(100)
a = np.floor(10*np.random.random((3,4)))
a

array([[5., 2., 4., 8.],
       [0., 1., 6., 8.],
       [1., 5., 8., 2.]])

In [374]:
np.random.seed(1)
np.random.randint(1,100,10)

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [375]:
np.random.randint(1,100,10)

array([77, 72,  7, 26, 51, 21, 19, 85, 12, 29])

In [376]:
np.random.seed(1)
np.random.randint(1,100,10)

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [377]:
np.random.seed(2)
np.random.randint(1,100,10)

array([41, 16, 73, 23, 44, 83, 76,  8, 35, 50])

In [378]:
np.random.seed(1)
np.random.randint(1,100,10)

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [379]:
np.random.seed(2)
np.random.randint(1,100,10)

array([41, 16, 73, 23, 44, 83, 76,  8, 35, 50])

In [380]:
a

array([[5., 2., 4., 8.],
       [0., 1., 6., 8.],
       [1., 5., 8., 2.]])

In [381]:
a.size

12

In [382]:
a.ravel()

array([5., 2., 4., 8., 0., 1., 6., 8., 1., 5., 8., 2.])

In [383]:
a

array([[5., 2., 4., 8.],
       [0., 1., 6., 8.],
       [1., 5., 8., 2.]])

In [387]:
a.reshape(1,-1)

array([[5., 2., 4., 8., 0., 1., 6., 8., 1., 5., 8., 2.]])

In [388]:
a.reshape(3,-1)

array([[5., 2., 4., 8.],
       [0., 1., 6., 8.],
       [1., 5., 8., 2.]])

In [389]:
a

array([[5., 2., 4., 8.],
       [0., 1., 6., 8.],
       [1., 5., 8., 2.]])

In [391]:
b=np.arange(20,29).reshape(3,-1)
b

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [393]:
np.hstack((a,b))

array([[ 5.,  2.,  4.,  8., 20., 21., 22.],
       [ 0.,  1.,  6.,  8., 23., 24., 25.],
       [ 1.,  5.,  8.,  2., 26., 27., 28.]])

In [394]:
c = a.reshape(-1,3)
c

array([[5., 2., 4.],
       [8., 0., 1.],
       [6., 8., 1.],
       [5., 8., 2.]])

In [395]:
np.vstack((c,b))

array([[ 5.,  2.,  4.],
       [ 8.,  0.,  1.],
       [ 6.,  8.,  1.],
       [ 5.,  8.,  2.],
       [20., 21., 22.],
       [23., 24., 25.],
       [26., 27., 28.]])

In [396]:
d = np.vstack((c,b))
d

array([[ 5.,  2.,  4.],
       [ 8.,  0.,  1.],
       [ 6.,  8.,  1.],
       [ 5.,  8.,  2.],
       [20., 21., 22.],
       [23., 24., 25.],
       [26., 27., 28.]])

In [400]:
d= np.vstack((d,np.arange(6).reshape(2,-1)))
d

array([[ 5.,  2.,  4.],
       [ 8.,  0.,  1.],
       [ 6.,  8.,  1.],
       [ 5.,  8.,  2.],
       [20., 21., 22.],
       [23., 24., 25.],
       [26., 27., 28.],
       [ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [403]:
a, b, c = np.vsplit(d,3)

In [404]:
a

array([[5., 2., 4.],
       [8., 0., 1.],
       [6., 8., 1.]])

In [405]:
b

array([[ 5.,  8.,  2.],
       [20., 21., 22.],
       [23., 24., 25.]])

In [406]:
c

array([[26., 27., 28.],
       [ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [407]:
d

array([[ 5.,  2.,  4.],
       [ 8.,  0.,  1.],
       [ 6.,  8.,  1.],
       [ 5.,  8.,  2.],
       [20., 21., 22.],
       [23., 24., 25.],
       [26., 27., 28.],
       [ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [414]:
s = np.vsplit(d, np.array([3,5,6]))
for m in s:
    print(m, end="\n"*3)

[[5. 2. 4.]
 [8. 0. 1.]
 [6. 8. 1.]]


[[ 5.  8.  2.]
 [20. 21. 22.]]


[[23. 24. 25.]]


[[26. 27. 28.]
 [ 0.  1.  2.]
 [ 3.  4.  5.]]




In [415]:
len(d)

9

In [420]:
np.vsplit(d,1)

[array([[ 5.,  2.,  4.],
        [ 8.,  0.,  1.],
        [ 6.,  8.,  1.],
        [ 5.,  8.,  2.],
        [20., 21., 22.],
        [23., 24., 25.],
        [26., 27., 28.],
        [ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])]

# Two types of copy - Shallow vs Deepcopy

In [421]:
a

array([[5., 2., 4.],
       [8., 0., 1.],
       [6., 8., 1.]])

In [434]:
x= a[:] # shallow copy

In [435]:
np.shares_memory(a,x)

True

In [437]:
y= a.copy() # deepcopy

In [438]:
y

array([[  5.,   2.,   4.],
       [  8., 100.,   1.],
       [  6.,   8.,   1.]])

In [439]:
a

array([[  5.,   2.,   4.],
       [  8., 100.,   1.],
       [  6.,   8.,   1.]])

In [440]:
x

array([[  5.,   2.,   4.],
       [  8., 100.,   1.],
       [  6.,   8.,   1.]])

In [441]:
np.shares_memory(a,y)

False

In [442]:
np.shares_memory(a,x)

True

In [443]:
x[1,1]=1000

In [444]:
x

array([[   5.,    2.,    4.],
       [   8., 1000.,    1.],
       [   6.,    8.,    1.]])

In [445]:
a

array([[   5.,    2.,    4.],
       [   8., 1000.,    1.],
       [   6.,    8.,    1.]])

In [446]:
y

array([[  5.,   2.,   4.],
       [  8., 100.,   1.],
       [  6.,   8.,   1.]])

In [447]:
y.base in a

False

In [448]:
x.base in a

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [449]:
a

array([[   5.,    2.,    4.],
       [   8., 1000.,    1.],
       [   6.,    8.,    1.]])

In [451]:
v = a.view()

In [452]:
v

array([[   5.,    2.,    4.],
       [   8., 1000.,    1.],
       [   6.,    8.,    1.]])

In [453]:
v.shape

(3, 3)

In [456]:
v

array([[   5.,    2.,    4.],
       [   8., 1000.,    1.],
       [   6.,    8.,    1.]])

In [457]:
a

array([[   5.,    2.,    4.],
       [   8., 1000.,    1.],
       [   6.,    8.,    1.]])

In [458]:
v[0,0]=90

In [459]:
v

array([[  90.,    2.,    4.],
       [   8., 1000.,    1.],
       [   6.,    8.,    1.]])

In [460]:
a

array([[  90.,    2.,    4.],
       [   8., 1000.,    1.],
       [   6.,    8.,    1.]])

In [462]:
v.base in a

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [463]:
v.flags.owndata

False

In [465]:
v.base is a

False

In [466]:
v.base is d

True

In [467]:
a.flags.owndata

False

In [468]:
d.flags.owndata

True

In [469]:
del d[0,0]

ValueError: cannot delete array elements

In [470]:
d

array([[  90.,    2.,    4.],
       [   8., 1000.,    1.],
       [   6.,    8.,    1.],
       [   5.,    8.,    2.],
       [  20.,   21.,   22.],
       [  23.,   24.,   25.],
       [  26.,   27.,   28.],
       [   0.,    1.,    2.],
       [   3.,    4.,    5.]])